title: "Rikki J Prince"
email: me@rikkijprince.com
description: "English language learning, science-based literature, reflective thinking, and some science-fiction."
baseurl: ""
url: "https://rikkijprince.com"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

repository: rikkijprince/rikkijprince

# Active site navigation is maintained in _includes/navbar.html.
